version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: always
        working_dir: /var/www
        volumes:
            - ./:/var/www
    nginx:
        image: nginx
        container_name: nginx
        restart: always
        working_dir: /var/www
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/ssl:/etc/nginx/ssl
